<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>CACH-OUT-Ionity</AssemblyName>
    <RootNamespace>CachOutIonity.Native</RootNamespace>
    <ApplicationIcon>..\desktop\app.ico</ApplicationIcon>
    <Company>Ionity Global (Pty) Ltd</Company>
    <Product>CACH OUT Ionity</Product>
    <Copyright>Copyright (c) Ionity Global (Pty) Ltd</Copyright>
    <FileVersion>1.1.0.0</FileVersion>
    <Version>1.1.0</Version>
    <AssemblyVersion>1.1.0.0</AssemblyVersion>
  </PropertyGroup>

</Project>